# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_DAC_0_0/system_DAC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_DAC_0_0 || ORIG_REF_NAME==system_DAC_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cordic_0_0/system_cordic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cordic_0_0 || ORIG_REF_NAME==system_cordic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_data_input_0_0/system_dac_data_input_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_data_input_0_0 || ORIG_REF_NAME==system_dac_data_input_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_200M_0/system_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_200M_0 || ORIG_REF_NAME==system_rst_ps7_0_200M_0} -quiet] -quiet

# XDC: /home/jason/Documents/Zynq/radio/radio.gen/sources_1/bd/system/system_ooc.xdc
