#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Nov 20 11:18:35 CST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
bin_path="/opt/intelFPGA/24.1/questa_fse/bin"
set -Eeuo pipefail
source sim_elaborate.do 2>&1 | tee elaborate.log

