######################################################################
#
# File name : sim_wave.do
# Created on: Thu Nov 20 11:18:35 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
