######################################################################
#
# File name : sim_simulate.do
# Created on: Thu Nov 20 11:18:35 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib sim_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim_wave.do}

view wave
view structure
view signals

do {sim.udo}

run 1000ns
