######################################################################
#
# File name : sim_elaborate.do
# Created on: Thu Nov 20 11:18:35 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/opt/intelFPGA/24.1/questa_fse/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L xbip_utils_v3_0_14 -L c_reg_fd_v12_0_10 -L xbip_dsp48_wrapper_v3_0_7 -L xbip_pipe_v3_0_10 -L c_addsub_v12_0_20 -L mult_gen_v12_0_23 -L axi_utils_v2_0_10 -L cordic_v6_0_24 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.sim xil_defaultlib.glbl -o sim_opt
