######################################################################
#
# File name : sim_compile.do
# Created on: Thu Nov 20 11:18:34 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/opt/intelFPGA/24.1/questa_fse/bin/vlib questa_lib/work
/opt/intelFPGA/24.1/questa_fse/bin/vlib questa_lib/msim

/opt/intelFPGA/24.1/questa_fse/bin/vlib questa_lib/msim/xil_defaultlib

/opt/intelFPGA/24.1/questa_fse/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/opt/intelFPGA/24.1/questa_fse/bin/vcom -64 -93 -work xil_defaultlib  \
"../../../../radio.gen/sources_1/ip/cordic_0/sim/cordic_0.vhd" \

/opt/intelFPGA/24.1/questa_fse/bin/vlog -64 -incr -mfcu -work xil_defaultlib  "+incdir+../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../radio.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../radio.gen/sources_1/bd/system/ipshared/6cfa/hdl" "+incdir+../../../../radio.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../radio.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../radio.srcs/sim_1/new/sim.v" \


# compile glbl module
/opt/intelFPGA/24.1/questa_fse/bin/vlog -work xil_defaultlib "glbl.v"

