domain_path: /home/jason/Documents/Zynq/radio/Vitis/radio_platform/export/radio_platform/sw/freertos_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/freertos_hello_world
template: freertos_hello_world
lang: c
